version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 2s
      retries: 10

  node-backend:
    build: ./node-backend
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: secret
      DB_NAME: testdb
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  apache:
    image: httpd:latest
    ports:
      - "80:80"       # сайт
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    depends_on:
      - node-backend